version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: veyron-mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - veyron-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.b.development
    container_name: veyron-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - veyron-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.f.development
    container_name: veyron-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - veyron-network

networks:
  veyron-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local