version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: veyron-mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - veyron-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: veyron-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://admin:password@mongodb:27017/veyron?authSource=admin
      - JWT_SECRET=veyron_secret_key
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - veyron-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: veyron-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - veyron-network

networks:
  veyron-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
