FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./

# En production, on installe uniquement les dépendances de production
RUN npm ci --only=production

COPY . .

RUN mkdir -p public/uploads public/images

# Deuxième étape pour réduire la taille de l'image finale
FROM node:20-alpine

WORKDIR /app

COPY --from=build /app .

EXPOSE 3000

# Utilisation de NODE_ENV=production pour optimiser les performances
ENV NODE_ENV=production

CMD ["node", "server.js"]