FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN mkdir -p public/uploads public/images

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY --from=build /app/public ./public
COPY --from=build /app/src ./src
COPY --from=build /app/config ./config
COPY --from=build /app/server.js ./

EXPOSE 3000

CMD ["node", "server.js"]