FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# En développement, on ne copie pas les fichiers car ils seront montés en volume
# COPY . .

RUN mkdir -p public/uploads public/images

EXPOSE 3000

# En développement, on utilise nodemon pour le rechargement à chaud
CMD ["npx", "nodemon", "server.js"]